# Generated by Django 4.0.5 on 2023-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanlength',
            name='vanlength',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
