# Generated by Django 4.0.5 on 2023-03-31 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_vanlength_vanlength'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('c_companyname', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('c_address', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('c_adressetc', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('c_order_notes', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('status', models.CharField(blank=True, choices=[('Создан', 'Создан'), ('Отменён', 'Отменён'), ('На хранении', 'На хранении'), ('Завершён', 'Завершён'), ('Передан в работу', 'Передан в работу'), ('Готов к получению', 'Готов к получению')], default='Ожидает подтверждения', max_length=30, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.RemoveField(
            model_name='tirestore',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoryOrder',
        ),
        migrations.DeleteModel(
            name='TireStore',
        ),
    ]
