# Generated by Django 4.0.5 on 2023-03-31 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_historyorders_data_alter_historyorders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyorders',
            name='data',
        ),
        migrations.AddField(
            model_name='historyorders',
            name='datecreate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
